name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - master  # or main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Install Angular CLI
        run: npm install -g @angular/cli@16.1.8    

      - name: Build Angular App
        run: ng build --configuration production --base-href /angular-gh-demo/

      - name: Zip Build Folder
        run: |
          cd dist
          zip -r angular-gh-demo.zip angular-gh-demo

      - name: Upload Artifact - Zipped Build
        uses: actions/upload-artifact@v3
        with:
          name: angular-gh-demo-zip
          path: dist/angular-gh-demo.zip

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist/angular-gh-demo
          clean: true

